### ISSUE TITLE
Error Loading Map File

### ISSUE THREAD

**Issue by braddorl** [ge0rg/aprsdroid#101]
I installed the latest OSM apk file for APRSdroid. Program worked great. Attempted to load the USA Map file on SDCARD after renaming file to aprsdroid.map. When I point APRSdroid to the map file on SDCARD from preferences I receive the error "Error loading map file null!!" I have tried to download and use the virginia.map file as well. I am having no luck installing a map file.

**Comment by ge0rg** [comment]
Please try a different file manager to choose the map. I've had success with the file chooser that is part of CyanogenMod as well as with Ghost Commander from Google Play.

If you can tell me which file manager you are trying, I can check if it is doing things differently and maybe adopt APRSdroid's code.

**Comment by braddorl** [comment]
Georg,
I figured out the problem, I think. I was attempting to save the file in a
folder on an external SDCARD. Once I save the file on the internal memory
in the root directory (i.e. not behind any folder) it works amazingly.
Unfortunately, I am not running a rooted device (Samsung Galaxy Tab3 7.0).
But if I may digress, where can I find information on the .xml file? I do
not have one loaded for aprsdroid, but I have one for Backcountry Navigator
that is beautiful. But try as I may to get the file to be recognized by
aprsdroid, I am unable to get it operational.

Thank you for an amazing product!
Randy

**Comment by ge0rg** [comment]
Can you tell me which file manager you are using to select the map / xml file? I suppose there is a bug in interpreting that file manager's results.

**Comment by dysinger** [comment]
I just downloaded an OSM build from a couple days ago.  I can't get any maps to work.  I tried up to date mapforge maps built yesterday. I tried the 2.3G USA.map listed on the download page.  None of it works.

**Comment by dysinger** [comment]
![osm-map-null](https://cloud.githubusercontent.com/assets/447/7058562/3dc47e52-ddff-11e4-96bc-3a27cc58bc17.png)

**Comment by dysinger** [comment]
BTW thanks for your work on this. I appreciate it.

**Comment by ge0rg** [comment]
Please try a different file manager to select the map file. I've tested it with Ghost Commander and the file manager built into CyanogenMod. If you call out additional file managers, I can add support for them into APRSdroid as well.

**Comment by TSellers2** [comment]
I'm confused as to how to use another file manager to select the map. I don't see that option in the aprsdroid preferences, it just defaults to to program's file manager.

**Comment by TargetDriver** [comment]
I downloaded the 2.5 GB US Map and dropped it in the root of my 32 GB SD card. I disconnected WiFi and restarted. On restart, APRSdroid warned me that it couldn't find the map at /storage/emulated/0...then it crashed and refused to recover even after I re-connected WiFi. A re-install convinced it to work again.

I figured I had not invested enough time or effort in the project so, I rooted the device, loaded a bunch of geekery and formatted the stick into 2 partitions (fat32 and ext4). I moved as much as I could from internal storage to the stick with "Link2SD". Now that I have 2 partitions on the SD, there are few apps that can't be moved. That still leaves me with less than 2 GB of available internal storage...not enough for the map.

I presumed that the internal storage forked with the external 2nd partition because it appeared to be contiguous...but, invisible and inaccessible as a discrete storage location to the file managers I'm using. It appears as /data/sdext2 to "Link2SD" so, I used a terminal emulator to copy the map from the fat32 partition to the root of /data/sdext2 and fired it up again.

With the WiFi off, it doesn't complain of not finding the map but, on the other hand, it still has the last resolution and range of Google maps showing up. I feel that I am close to resolving this if I can tell it to stop using Google maps. I saw that dysinger sc'd his preferences showing "Map File Name". I cannot find that in my preferences, at all. How do I set the map preference?

Here's what I'm running:
APRSdroid version 1.3.0 2015-04-03
Qualcomm Snapdragon 400/410 1.21 GHz
4x ARM Cortex-A53 @ 1.21 GHz
LGLK430 (e7iilte_spr_us)
Android version 5.0.1
Kernel Version 3.10.49-g08a72s8

My intent is to have the tablet completely untethered from cellular service so my mobile APRS station will function in the event of a massive power outage or Zombie Apocalypse. Being a Red Cross communications volunteer and seeing as how RC is going digital, I'm thinking this might come in handy.

73
KD8REK

**Comment by ChuckBland** [comment]
I have a Samsng TAB4, running Android 4.4.2.

APRSDroid version 1.3.0-39-g3d4e2cf 2016-02-23, the OSM build.

I am getting the same error message illustrated by dysinger in his message above.

- I have downloaded the usa map file twice.
- I have tried it with the names USA.map and aprsdroid.map
- I have ran APRSDroid from my card and from internal storage
- I have installed Ghost Commander, as was recommended in an earlier posting. (I don't see why this would have made any difference, since the error occurs inside APRSDRoid and not the file manager.)
- I do not have enough room on internal storage to put the map file on internal storage.

Has anyone figured out what to do about this?

Chuck Bland
NA6BR

**Comment by ge0rg** [comment]
Very sorry for the confusion. There was another change in Android 4.4 that caused Ghost Commander and other file managers to be hidden from the system file picker, and the built-in file picker to stop working.

I have fixed APRSdroid now, please test [this APK](http://aprsdroid.org/download/builds/APRSdroid-gl-2016-03-07_osm.apk) and let me know.

P.S: You can also uninstall Ghost Commander again ;-)

**Comment by ChuckBland** [comment]
Georg,

The error persists with  the new apk.

**Comment by braddorl** [comment]
Chuck,
I had the same issue as dysinger. I was able to overcome by placing the map
in the root folder. What is ironic is I still get the same error but the
map works and the program works well. No clue just experience.

Randy
N1VTT

**Comment by ChuckBland** [comment]
Just tried it. The file has  been  in  the  root of my sdcard. Still no joy.

**Comment by braddorl** [comment]
I'm using the internal sdcard, which I just realized you are trying to use
external. I never got to work on the external.

**Comment by ChuckBland** [comment]
So I have been trying to use the 2GB usa file... which doesnt fit on my
internal storge. I guess I should at leat get the CA file and start with
that.

**Comment by ge0rg** [comment]
@ChuckBland I've tested the new build on a Galaxy S4 mini with 4.4.2, which should be near enough... Really strange. 

The fallback solution would be the following:

 * tap "Map file" in Aprsdroid preferences 
 * in the file chooser swipe from the left to open the menu 
 * from the bottom of the menu select Ghost Commander 
 * in Ghost Commander, choose the map file

**Comment by braddorl** [comment]
Just played with the new apk and was able to get it to load correctly by
using es file explorer vice the built-in selector.

**Comment by ChuckBland** [comment]
My flight just landed. I will try this later. Thanks everyone!

**Comment by ChuckBland** [comment]
George's directions worked, even with the map file on the external card.

Thanks!

**Comment by LU1XDH** [comment]
Hi everyone! i fixed it up installing ghost commander on my android. So, i left the original name of the map (NO aprsdroid.map) example: argentina, and put 3 differents maps (Argentina, Chile, Uruguay) on the SDcard and i choose from preferens the map i´ll use.

Thanks!
