### ISSUE TITLE
Google maps not loading

### ISSUE THREAD

**Issue by coldfire22x** [ge0rg/aprsdroid#284]
Google Map and Satellite views show nothing.  OpenStreetMap renders, albeit very slowly.

Pixel 3 on Android 11.

![Screenshot_20200929-114950](https://user-images.githubusercontent.com/1269012/94602739-2108ea80-024a-11eb-87fc-3550ce1a83a2.png)

![Screenshot_20200929-114957](https://user-images.githubusercontent.com/1269012/94602763-29612580-024a-11eb-9c45-cc29d798847a.png)

![Screenshot_20200929-115002](https://user-images.githubusercontent.com/1269012/94602788-2fef9d00-024a-11eb-98dc-1145f8d266dd.png)

**Comment by k1ky** [comment]
v1.60b Google Maps and Satellite views not working on latest Android 10, Samsung Note 9 and Samsing A51.

**Comment by ge0rg** [comment]
Thanks for the report. There was an issue with my local build system that happened after 52a63a489fd4147343734c528c43b268bfa00e1f and made my APKs not render the Google Maps. I've published 1.6.0c which should hopefully work now.

**Comment by k1ky** [comment]
It's  working now after update this morning. Version still shows 1.60b

**Comment by coldfire22x** [comment]
Confirmed 1.6.0c is working on Pixel 3/Android 11!  Thanks!
